library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from hust_library import views

urlpatterns = [
    path('', views.index_view, name='index'),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.logout_then_login, name='logout'),
    path('is_admin/', views.is_admin_view, name='is_admin'),
    path('self_inf/', views.self_inf_view, name='self_inf'),
    path('loans/', views.loans_view, name='loans'),
    path('loaned/', views.loaned_view, name='loaned'),
    path('loaned/renew/<int:pk>', views.renew_view, name='renew'),
    path('tickets/', views.tickets_view, name='tickets'),
    path('tickets/handle/<int:pk>/',
         views.ticket_handle_view, name='ticket_handle'),
    path('books/', views.books_view, name='books'),
    path('books/<int:pk>/', views.BookView.as_view(), name='book'),
    path('administrator/', views.administrator_view, name='administrator'),
    path('administrator/books_manage/',
         views.books_manage_view, name='books_manage'),
    path('administrator/books_manage/<int:pk>/',
         views.book_manage_view, name='book_manage'),
    path('administrator/books_manage/new/',
         views.new_book_view, name='new_book'),
    path('administrator/books_manage/edit/<int:pk>/',
         views.edit_book_view, name='edit_book'),
    path('administrator/books_manage/delete/<int:pk>/',
         views.delete_book_view, name='delete_book'),
    path('administrator/books_manage/write/<int:book_pk>/',
         views.write_view, name='write'),
    path('administrator/books_manage/<int:book_pk>/write/new/',
         views.new_write_view, name='new_write'),
    path('administrator/books_manage/write/edit/<int:pk>/',
         views.edit_write_view, name='edit_write'),
    path('administrator/books_manage/write/delete/<int:pk>/',
         views.delete_write_view, name='delete_write'),
    path('administrator/books_manage/store/<int:book_pk>/',
         views.store_view, name='store'),
    path('administrator/books_manage/<int:book_pk>/store/new/',
         views.new_store_view, name='new_store'),
    path('administrator/books_manage/store/edit/<int:pk>/',
         views.edit_store_view, name='edit_store'),
    path('administrator/books_manage/store/delete/<int:pk>/',
         views.delete_store_view, name='delete_store'),
    path('administrator/readers_manage/',
         views.readers_manage_view, name='readers_manage'),
    path('administrator/readers_manage/<int:pk>/',
         views.reader_manage_view, name='reader_manage'),
    path('administrator/readers_manage/new/',
         views.new_reader_view, name='new_reader'),
    path('administrator/readers_manage/edit/<int:pk>/',
         views.edit_reader_view, name='edit_reader'),
    path('administrator/readers_manage/delete/<int:pk>/',
         views.delete_reader_view, name='delete_reader'),
    path('administrator/readers_manage/set_password/<int:pk>/',
         views.set_password_view, name='set_password'),
    path('administrator/borrow_manage/',
         views.borrow_manage_view, name='borrow_manage'),
    path('administrator/return_manage/',
         views.return_manage_view, name='return_manage')
]

hust_library/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


class Ticket(models.Model):
    price = models.DecimalField(max_digits=6, decimal_places=2)
    time = models.DateTimeField()
    quantity = models.SmallIntegerField(default=1)
    description = models.CharField(max_length=150)
    address = models.CharField(max_length=150)
    state = models.IntegerField(default=0)
    reader = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="ticket_reader_id")

    def __str__(self):
        return self.description


class Book(models.Model):
    name = models.CharField(max_length=150)
    publish = models.CharField(max_length=150)
    time = models.IntegerField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    keyword = models.CharField(max_length=150)
    stock = models.SmallIntegerField(default=0)
    supplier = models.CharField(max_length=10, null=False)
    seriesNo = models.IntegerField()

    class Meta:
        unique_together = ("name", "publish", "time", "price", "keyword", "stock", "supplier", "seriesNo")

    def __str__(self):
        return self.name


class Write(models.Model):
    writer = models.CharField(max_length=150)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return self.writer

    class Meta:
        unique_together = ("writer", "book")


class Store(models.Model):
    location = models.CharField(max_length=150)
    state = models.SmallIntegerField(default=1)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return self.location


class Loan(models.Model):
    time = models.DateTimeField()
    state = models.SmallIntegerField(default=0)
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    reader = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="loan_reader_id")


class BookShortage(models.Model):
    name = models.CharField(max_length=150)
    publish = models.CharField(max_length=150)
    supplier = models.CharField(max_length=10)
    quantity = models.IntegerField(null=False, validators=[
        MinValueValidator(10),
        MaxValueValidator(9999)
    ])
    registrationDate = models.IntegerField()

    def __str__(self):
        return self.name


class Reader(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    address = models.CharField(max_length=300)
    balance = models.DecimalField(max_digits=10, decimal_places=2)
    credit_rating = models.IntegerField()

    def __str__(self):
        return self.user.username

class Supplier(models.Model):
    name = models.CharField(max_length=30)
    phoneNumber = models.CharField(max_length=11)
    supplyInfo = models.TextField()

    def __str__(self):
        return self.name

hust_library/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from . import models


class BorrowManageForm(forms.Form):
    store_id = forms.IntegerField(label='藏书号')
    username = forms.CharField(label='用户名', max_length=150)


class ReturnManageForm(forms.Form):
    store_id = forms.IntegerField(label='藏书号')
    is_broken = forms.BooleanField(label='书籍损坏', required=False)


class BookForm(forms.ModelForm):
    class Meta:
        model = models.Book
        fields = ['name', 'publish', 'time', 'price']
        labels = {
            'name': _('书名'),
            'publish': _('出版社'),
            'time': _('出版时间'),
            'price': _('价格')
        }


class ReaderForm(forms.Form):
    username = forms.CharField(label='用户名', max_length=150)
    last_name = forms.CharField(label='姓', max_length=150)
    first_name = forms.CharField(label='名', max_length=30)
    email = forms.EmailField(label='邮箱')
    # address = forms.CharField(label='地址', max_length=300)
    # balance = forms.DecimalField(label='账户余额', max_digits=10, decimal_places=2)
    # creditLevel = forms.IntegerField(label='信用等级')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <title>华中科技大学图书馆</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.bootcss.com/bootstrap-table/1.14.2/bootstrap-table.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        type="text/css">
    <link rel="stylesheet" href="{% static 'css/theme.css' %}" type="text/css">
    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap-table/1.14.2/bootstrap-table.min.js"></script>

    <style>
        :root {
            --primary-color: #6baed6; /* 浅蓝色 */
            --secondary-color: #eff3ff; /* 非常浅的蓝色 */
            --text-color: #333333; /* 深灰色文字 */
            --link-color: #4a90e2; /* 明亮的蓝色链接 */
        }

        body {
            font-family: 'Noto Sans SC', sans-serif;
            background-color: var(--secondary-color);
            color: var(--text-color);
        }

        .navbar, .dropdown-menu, footer {
            background-color: var(--primary-color);
        }

        .nav-link, .navbar-brand, .dropdown-item, footer {
            color: #fff;
        }

        .nav-link:hover, .dropdown-item:hover {
            color: var(--link-color);
            background-color: transparent;
        }

        a, a:hover, a:focus {
            text-decoration: none;
            color: var(--link-color);
        }

        footer {
            background-color: var(--primary-color);
            color: #fff;
        }

        .nav-tabs {
            border-bottom: 1px solid rgba(0, 0, 0, 0.1);
        }

        .nav-tabs .nav-link.active, .nav-tabs .nav-item.show .nav-link {
            color: #495057;
            background-color: transparent;
            border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(236, 236, 236, 1);
        }
        .navbar-nav {
            margin-right: 0 !important; /* 确保导航项向左对齐 */
        }
    
        .navbar-collapse {
            justify-content: start !important; /* 在Flex容器中靠左对齐内容 */
        }

         .navbar .dropdown-menu, .navbar .dropdown-menu.bg-primary {
            background-color: var(--primary-color) !important; /* 为.bg-primary类设置新的背景色 */
        }

        .navbar .dropdown-menu .dropdown-item, .navbar .dropdown-menu.bg-primary .dropdown-item {
            color: #fff !important; /* 设置下拉菜单项的文字颜色 */
        }

        .navbar .dropdown-menu .dropdown-item:hover, .navbar .dropdown-menu.bg-primary .dropdown-item:hover {
            color: #fff !important; /* 鼠标悬停时的文字颜色 */
            background-color: var(--link-color) !important; /* 鼠标悬停时的背景色 */
        }
        .content {
        min-height: 450px; /* 可以根据需要调整这个值 */
        padding: 20px; /* 添加一些内边距以改善视觉效果 */
        }
        

    </style>



    {% if messages %}
    <script>
        {% for msg in messages %}
        alert('{{ msg.message }}');
        {% endfor %}
    </script>
    {% endif %}
</head>

<body style="background-color: rgba(0,0,0,0.1)">
    {% block lead %}
        
     <nav class="navbar navbar-expand-md navbar-dark">
        <div class="container">
            <a class="navbar-brand d-none d-md-block" href="{% url 'index' %}" style>
                <b>华中科技大学图书馆</b>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar18" aria-controls="navbar18" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar18">
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'books' %}">图书信息</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tickets' %}">订单信息</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">借阅信息</a>
                        <div class="dropdown-menu bg-primary">
                            <a class="dropdown-item text-light" href="{% url 'loans' %}">借书记录</a>
                            <a class="dropdown-item text-light" href="{% url 'loaned' %}">待还书籍</a>
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-light" href="#" id="navbardrop" data-toggle="dropdown">
                            {% if request.user.is_authenticated %}
                            {{ request.user.username }} 您好
                            {% else %}
                            欢迎
                            {% endif %}
                        </a>
                        <div class="dropdown-menu bg-primary">
                            {% if request.user.is_authenticated %}
                            <a class="dropdown-item text-light" href="{% url 'self_inf' %}">个人信息</a>
                            <a class="dropdown-item text-light" href="{% url 'logout' %}">登出</a>
                            {% else %}
                            <a class="dropdown-item text-light" href="{% url 'login' %}">登录</a>
                            {% endif %}
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% endblock %}

    <div class="content">
        {% block content %}
        <!-- 页面主要内容 -->
        {% endblock %}
    </div>

</body>


<footer class="text-muted py-4 bg-dark">
    <div class="container">
        <p class="mb-1">© 2023 华中科技大学图书馆</p>
        <p class="mb-0">联系我们: <a href="mailto:xiaokaizhang@hust.edu.cn">xiaokaizhang@hust.edu.cn</a></p>
    </div>
</footer>






</html>

templates/book.html
{% extends "base.html" %}

{% block content %}
<div class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-12" style="">
                <h2>图书信息</h2>
                <hr class="mb-4">
            </div>
        </div>
        <div class="row">
            <div class="p-3 col-md-8">
                <table class="table table-bordered table-hover table-striped">
                    <tbody>
                        <tr>
                            <th scope="row">编号</th>
                            <td>{{ book.id }}</td>
                        </tr>
                        <tr>
                            <th scope="row">书名</th>
                            <td>{{ book.name }}</td>
                        </tr>
                        <tr>
                            <th scope="row">作者</th>
                            <td>
                                {% for write in book.write_set.all %}
                                {{ write.writer }}
                                {% endfor %}
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">出版社</th>
                            <td>{{ book.publish }}</td>
                        </tr>
                        <tr>
                            <th scope="row">出版时间</th>
                            <td>{{ book.time }}</td>
                        </tr>
                        <tr>
                            <th scope="row">定价</th>
                            <td>{{ book.price }}</td>
                        </tr>
                        <tr>
                            <th scope="row">关键字</th>
                            <td>{{ book.keyword }}</td>
                        </tr>
                        <tr>
                            <th scope="row">存货量</th>
                            <td>{{ book.stock }}</td>
                        </tr>
                        <tr>
                            <th scope="row">供书商</th>
                            <td>{{ book.supplier }}</td>
                        </tr>
                        <tr>
                            <th scope="row">丛书号</th>
                            <td>{{ book.seriesNo }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-12">
                <h3>馆藏书籍</h3>
                <hr class="mb-4">
            </div>
        </div>
        {% if book.store_set.all.count == 0 %}
        <div class="row">
            <div class="col-md-12">
                <h4> 没有馆藏 </h4>
            </div>
        </div>
        {% else %}
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-8 p-3">
                    <table class="table table-hover table-striped table-bordered">
                        <thead class="thead-inverse">
                            <tr>
                                <th scope="col">编号</th>
                                <th scope="col">馆藏地点</th>
                                <th scope="col">状态</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for store in book.store_set.all %}
                            <tr>
                                <td>{{ store.id }}</td>
                                <td>{{ store.location }}</td>
                                <td>
                                    {% if store.state == 0 %}
                                    借出
                                    {% elif store.state == 1 %}
                                    在馆
                                    {% else %}
                                    损坏
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/books.html
{% extends "base.html" %}

{% block content %}
<div class="py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <form class="form-inline" action="{% url 'books' %}" method="get">
                    <div class="input-group">
                        <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Search"
                            name="name" required>
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% if 'name' in request.GET %}
<div class="py-4">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>搜索结果</h2>
                <hr>
                {% if is_empty %}
                <p class="lead">搜索无结果</p>
                {% endif %}
                {% for book in books %}
                <a href="{% url 'book' book.id %}">
                    <p class="lead">{{ book.name }}</p>
                </a>
                <p>
                    作者：
                    {% for write in book.write_set.all %}
                    {{ write.writer }}
                    {% endfor %}
                    出版社：{{ book.publish }} 出版时间：{{ book.time }}
                </p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/books_manage.html
{% extends "administrator.html" %}

{% block content %}
<div class="py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <form class="form-inline" action="{% url 'books_manage' %}" method="get">
                    <div class="input-group">
                        <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Bookname"
                            name="name" required>
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% if 'name' in request.GET %}
<div class="py-4">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>搜索结果</h2>
                <hr>
                {% if is_empty %}
                <p class="lead">搜索无结果</p>
                {% endif %}
                {% for book in books %}
                <p class="lead">
                    <a href="{% url 'book_manage' book.id %}">
                        {{ book.name }}
                    </a>
                    <a class="btn btn-outline-primary ml-4" href="{% url 'delete_book' book.id %}">删除</a>
                </p>
                <p>
                    作者:
                    {% for write in book.write_set.all %}
                    {{ write.writer }}
                    {% endfor %}
                    出版社:{{ book.publish }} 出版时间:{{ book.time }}
                </p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    {#<div class="py-5">#}
    {#    <div class="container">#}
    {#        <div class="row">#}
    {#            <div class="mx-auto col-md-9">#}
    {#                <h1 class="mb-3 text-center">本馆介绍</h1>#}
    {#                <p>&nbsp; &nbsp; 华中科技大学图书馆现设主馆、医学分馆、东区分馆三个馆区，馆舍总面积64581平方米，各类阅览室33个，可用座位6500多个，其中电子阅览室3个，计算机近300台。</p>#}
    {#                <h3 class="mb-3">文献信息资源体系建设</h3>#}
    {#                <p>&nbsp; &nbsp;#}
    {#                    图书馆积极服务华中科技大学的建设和发展，大力加强文献信息资源体系建设，优先发展电子资源，适度发展印刷资源。馆藏文献涵盖理、工、医、文、管等九大学科门类。&nbsp;&nbsp;<br>&nbsp;#}
    {#                    &nbsp; 截至2017年12月31日，馆藏文献总量为1045.98万册。医学古籍特藏是馆藏特色之一，三种古籍入选《国家珍贵古籍名录》。&nbsp;<br>&nbsp; &nbsp;#}
    {#                    现有中、外文数据库577个，数据库总量在全国高校名列前茅。一批高水平数据库为学校教学、科研和学科建设提供了强大的文献信息保障。</p>#}
    {#                <h3 class="mb-3" style="">文献信息服务体系建设</h3>#}
    {#                <p>&nbsp; &nbsp; 为服务好学校改革发展和学科需要，近年来，图书馆着力建设文献信息服务体系，拓宽知识服务边界，取得了良好效果。&nbsp;&nbsp;<br>&nbsp; &nbsp;#}
    {#                    依托丰富的馆藏资源和专业人才优势，图书馆开展了以职能部门和院系需求为目标，以决策支持服务和特色学科服务为中心的学科情报分析、定题及专利服务，为学校“双一流”建设当好科技情报的“千里眼”“顺风耳”。&nbsp;&nbsp;<br>&nbsp;#}
    {#                    &nbsp; 图书馆还为全校师生提供信息检索教学、科技查新、馆际互借与文献传递等多种形式的专题服务，面向全校各院系、各学科、各大科学平台开展了有针对性的学科服务，服务对象已延伸到校外。</p>#}
    {#                <h3 class="mb-3">校园文化建设</h3>#}
    {#                <p>&nbsp; &nbsp;#}
    {#                    除做好各项读者服务基础工作外，图书馆还不断拓展和深化服务，积极参与学校人才培养、信息化建设和校园文化建设。馆舍空间和多媒体空间、视频播放系统、高清视听室、学术报告厅等独特资源全年向院系和师生开放，学术大咖、科学前沿报告，高雅艺术、主题展览，精选好书、优选视频纷纷走进图书馆，与青年学子面对面。2014年开始打造的“一本好书，与你同行”系列阅读推广活动深受学生喜爱，2017年世界读书日专题活动“琅琅读书声”在第二届高校图书馆阅读推广案例大赛上荣获二等奖。#}
    {#                </p>#}
    {#                <h3 class="mb-3">“智慧化”图书馆建设</h3>#}
    {#                <p>&nbsp; &nbsp;#}
    {#                    随着学校的快速发展，师生读者对泛在服务的需求越来越迫切，传统图书馆变身智慧图书馆已是大势所趋。近年来，图书馆不断加强数字化基础工作，致力于“智慧化”的探索。除广为人知的无线射频识别系统（RFID）等数字化系统外，创新性地建设了网络安全多维度防护、业务大数据平台、自建数据私有云、手机借还、读者蓝牙物联、高精度三维导航等特有的服务与应用平台，确保数据有容量、安全有保障、服务有智能、读者有感知，初步实现了“智慧化”图书馆的雏形。#}
    {#                </p>#}
    {#                <p>&nbsp; &nbsp; 秉承“读者第一，服务育人”的办馆宗旨，图书馆在华中科技大学双一流的征程中，正向着一流研究型图书馆的目标努力奋进！</p>#}
    {#            </div>#}
    {#        </div>#}
    {#    </div>#}
    {#</div>#}

    {#    <div class="container"#}
    {#         style="display: flex;#}
    {#                align-items: center; /* 垂直居中 */#}
    {#                justify-content: center; /* 水平居中 */#}
    {#                height: 100%;">#}
    {#        <div class="row">#}
    {#            <div class="col-md-12 text-center">#}
    {#                <h2 class="font-weight-bold" style="font-size: 36px; color: #6baed6; margin-bottom: 30px;">#}
    {#                    欢迎来到华中科技大学图书馆</h2>#}
    {#                <p class="text-muted" style="font-size: 20px;">在这里，你可以探索丰富的知识宝库。</p>#}
    {#            </div>#}
    {#        </div>#}
    {#    </div>#}
    
{#    #}
{#    <div class="content d-flex align-items-center justify-content-center">#}
{#        <div class="container text-center">#}
{#            <h2 class="font-weight-bold" style="font-size: 36px; color: #6baed6; margin-bottom: 30px;">#}
{#                欢迎来到华中科技大学图书馆</h2>#}
{#            <p class="text-muted" style="font-size: 20px;">在这里，你可以探索丰富的知识宝库。</p>#}
{#        </div>#}
{#    </div>#}
{#    #}
{#    <div class="image-container mb-5">#}
{#        <img src="{% static 'images/library.png' %}" alt="图书馆图片">#}
{#    </div>#}
    <div class="container" style="min-height: 70vh; /* 使用视口高度作为最小高度 */
                                  display: flex;
                                  align-items: center; /* 垂直居中 */
                                  justify-content: center; /* 水平居中 */">
        <div class="row align-items-center justify-content-center">
            <!-- 文字部分 -->
            <div class="col-lg-6 text-center mb-4 mb-lg-0">
                <h2 class="font-weight-bold" style="color: #6baed6;">欢迎来到华中科技大学图书馆</h2>
                <p class="text-muted">在这里，你可以探索丰富的知识宝库。</p>
            </div>

            <!-- 图片部分 -->
            <div class="col-lg-6">
                <img src="{% static 'images/library.png' %}" alt="图书馆图片" class="img-fluid">
            </div>
        </div>
    </div>



{% endblock %}

templates/loaned.html
{% extends "base.html" %}

{% block content %}
<div class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>待还书籍</h2>
                <hr class="mb-4">
            </div>
        </div>
        {% if is_empty %}
        <h4>您没有待还书籍</h4>
        {% else %}
        <div class="row">
            <div class="col-md-12 p-3">
                <table class="table table-hover table-striped table-bordered">
                    <thead class="thead-inverse">
                        <tr>
                            <th scope="col">书名</th>
                            <th scope="col">藏书号</th>
                            <th scope="col">还书日期</th>
                            <th scope="col">剩余天数</th>
                            <th scope="col">续借</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for loan in loaned %}
                        <tr>
                            <td>
                                <a href="{% url 'book' loan.loan.store.book.id %}">{{ loan.loan.store.book.name }}</a>
                            </td>
                            <td>{{ loan.loan.store.id }}</td>
                            <td>{{ loan.date }}</td>
                            <td>
                                {% if loan.remain < 0 %}
                                已逾期
                                {% else %}
                                {{ loan.remain }}
                                {% endif %}
                            </td>
                            <td>
                                {% if loan.remain < 0 or loan.loan.state != 0 %}
                                无法续借
                                {% else %}
                                <a href="{% url 'renew' loan.loan.id %}">续借</a>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/loans.html
{% extends "base.html" %}

{% block content %}
<div class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>借阅记录</h2>
                <hr class="mb-4">
            </div>
        </div>
        {% if is_empty %}
        <h4> 您没有借阅信息 </h4>
        {% else %}
        <div class="row">
            <div class="col-md-12 p-3">
                <table class="table table-hover table-striped table-bordered">
                    <thead class="thead-inverse">
                        <tr>
                            <th scope="col">书名</th>
                            <th scope="col">藏书号</th>
                            <th scope="col">时间</th>
                            <th scope="col">操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for loan in loans %}
                        <tr>
                            <td>
                                <a href="{% url 'book' loan.store.book.id %}">{{ loan.store.book.name }}</a>
                            </td>
                            <td>{{ loan.store.id }}</td>
                            <td>{{ loan.time }}</td>
                            <td>
                                {% if loan.state == 0 %}
                                借书
                                {% elif loan.state == 1 %}
                                还书
                                {% else %}
                                续借
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/return_manage.html
{% extends "administrator.html" %}

{% block content %}
<div class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>归还书籍</h2>
                <hr class="mb-4">
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <form method="post" action="{% url 'return_manage' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>藏书号</label>
                        <input type="number" name="store_id" required class="form-control">
                    </div>
                    <div class="form-group">
                        <div class="form-check my-3">
                            <input class="form-check-input" type="checkbox" name="is_broken" id="id_is_broken"
                                value="on">
                            <label class="form-check-label" for="id_is_broken">书籍损坏</label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">还书</button>
                </form>
            </div>
        </div>

    </div>
</div>
{% endblock %}